(G-CODE GENERATED BY FLATCAM v8.993 - www.flatcam.org - Version Date: 2020/06/05)

(Name: 0_8)
(Type: G-code from Excellon)
(Units: MM)

(Created on Wednesday, 10 June 2026 at 08:49)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.7)
(Tool: 2 -> Dia: 0.78)
(Tool: 3 -> Dia: 0.8)
(Tool: 4 -> Dia: 0.9)
(Tool: 5 -> Dia: 1.0)
(Tool: 6 -> Dia: 1.0)
(Tool: 7 -> Dia: 1.1)
(Tool: 8 -> Dia: 1.3)
(Tool: 9 -> Dia: 2.0)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 100.0)
(Tool: 2 -> Feedrate: 100.0)
(Tool: 3 -> Feedrate: 100.0)
(Tool: 4 -> Feedrate: 100.0)
(Tool: 5 -> Feedrate: 100.0)
(Tool: 6 -> Feedrate: 100.0)
(Tool: 7 -> Feedrate: 100.0)
(Tool: 8 -> Feedrate: 100.0)
(Tool: 9 -> Feedrate: 100.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)
(Tool: 5 -> Feedrate Rapids: 1500)
(Tool: 6 -> Feedrate Rapids: 1500)
(Tool: 7 -> Feedrate Rapids: 1500)
(Tool: 8 -> Feedrate Rapids: 1500)
(Tool: 9 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.89)
(Tool: 2 -> Z_Cut: -1.89)
(Tool: 3 -> Z_Cut: -1.89)
(Tool: 4 -> Z_Cut: -1.89)
(Tool: 5 -> Z_Cut: -1.89)
(Tool: 6 -> Z_Cut: -1.89)
(Tool: 7 -> Z_Cut: -1.89)
(Tool: 8 -> Z_Cut: -1.89)
(Tool: 9 -> Z_Cut: -1.89)

(Tools Offset: )
(Tool: 3 -> Offset Z: -0.0)

(DEPTH_PER_CUT: )
(Tool: 1 -> DeptPerCut: 0.5)
(Tool: 2 -> DeptPerCut: 0.5)
(Tool: 3 -> DeptPerCut: 0.5)
(Tool: 4 -> DeptPerCut: 0.5)
(Tool: 5 -> DeptPerCut: 0.5)
(Tool: 6 -> DeptPerCut: 0.5)
(Tool: 7 -> DeptPerCut: 0.5)
(Tool: 8 -> DeptPerCut: 0.5)
(Tool: 9 -> DeptPerCut: 0.5)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)
(Tool: 5 -> Z_Move: 2)
(Tool: 6 -> Z_Move: 2)
(Tool: 7 -> Z_Move: 2)
(Tool: 8 -> Z_Move: 2)
(Tool: 9 -> Z_Move: 2)

(Z Start: None mm)
(Z End: 2.0 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.9500 ...   99.4000  mm)
(Y range:    3.1500 ...   85.0500  mm)

(Spindle Speed: 10000.0 RPM)
G21
G90
G94



G00 Z2.0000

G01 F100.00
M03 S10000
G4 P5.0
G00 X60.4200 Y40.3700
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X60.4200 Y32.7500
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X77.5550 Y33.7600
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X77.6450 Y30.5000
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X85.2650 Y30.5000
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X85.1750 Y33.7600
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X85.1650 Y37.1300
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
G00 X77.5450 Y37.1300
G01 Z-0.5000
G01 Z0
G00 Z2.0000
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G01 Z-1.5000
G01 Z0
G00 Z2.0000
G01 Z-1.8900
G01 Z0
G00 Z2.0000
M05
G00 Z2.00
G00 X0.0 Y0.0

